### ISSUE TITLE
Facebook link is obsolete or non-public

### ISSUE THREAD

**Issue by mikini** [fossi-foundation/fossi-foundation.github.io#7]
The link to Facebook (https://www.facebook.com/fossifoundation) in the [right pane](https://github.com/fossi-foundation/fossi-foundation.github.io/blob/master/_layouts/default.html#L28) of [the homepage](https://fossi-foundation.org/) seems to be to an obsolete or non-public Facebook presence. I see the following message when accessing it:

> Sorry, this content isn't available right now
> The link you followed may have expired, or the page may only be visible to an audience you're not in.

I haven't succeeded in locating other Facebook presences of FOSSi.

**Comment by wallento** [comment]
Sorry for getting to that this late. You are absolutely right, the Facebook page was actually deleted with my personal account. We didn't really maintain it should remove it.
