### ISSUE TITLE
GitHub ICON

### ISSUE THREAD

**Issue by M-SAI-SOORYA** [fossi-foundation/fossi-foundation.github.io#82]
Hi! this is Soorya, the reason i raised issue is that, when contributers go to Gsoc page they find for github link in the home or web page, of fossi foundation
We need to add github icon or image on top right corner or anywhere...it will be easy for contributers to move to the github page quickly!

**Comment by imphil** [comment]
Thanks for your bug report! Would you mind opening a pull request fixing the issue?

**Comment by gaurab-khanal** [comment]
Hi, This is Gaurab. I am new to open source. Can I contribute to this? Please assign me this issue.
